Repository kpn/combadge, pull requests merged in 2023-04, with the labels that each got.

#20 FIX: support header annotation in service definition
  combadge/support/http/request.py
  combadge/support/httpx/backends/sync.py
  tests/integration/cassettes/test_httpbin/test_headers.yaml
  tests/integration/test_httpbin.py
Labels: bug

#21 FIX: pass headers for async request definitions
  combadge/support/httpx/backends/async_.py
  tests/integration/cassettes/test_httpbin/test_headers_async.yaml
  tests/integration/cassettes/test_httpbin/test_headers_sync.yaml
  tests/integration/test_httpbin.py
Labels: bug

#22 NEW: allow for callable default func arguments
  combadge/core/request.py
  tests/integration/cassettes/test_httpbin/test_headers_async.yaml
  tests/integration/cassettes/test_httpbin/test_headers_sync.yaml
  tests/integration/test_httpbin.py
Labels: enhancement

#23 BREAK: merge `ErrorResponse.raise_for_result()` and `expect()`, resolves #18
  combadge/core/interfaces.py
  combadge/core/request.py
  combadge/core/response.py
  combadge/support/soap/response.py
  poetry.lock
  pyproject.toml
  tests/core/test_binder.py
  tests/core/test_response.py
  tests/integration/test_country_info_service.py
  tests/integration/test_httpbin.py
  tests/integration/test_number_conversion.py
Labels: enhancement, breaking-change
