Repository kpn/combadge, pull requests merged in 2024-10, with the labels that each got.

#130 OPT: bump Ruff ⬆️
  poetry.lock
  pyproject.toml
  tests/integration/test_country_info_service.py
  tests/integration/test_httpbin.py
  tests/integration/test_number_conversion.py
  tests/integration/test_weather.py
Labels: dependencies

#131 FIX: do not wrap `CancelledError` into `BackendError`, fixes #129 🐛
  combadge/core/errors.py
Labels: bug

#132 FIX: do not wrap `CancelledError` into `BackendError` 🐛
  combadge/core/errors.py
  tests/core/test_errors.py
Labels: bug

#133 OPT: Support list query parameters
  combadge/support/http/markers/request.py
  tests/integration/cassettes/test_httpbin/test_query_params.yaml
  tests/integration/test_httpbin.py
Labels: enhancement

#134 OPT: remove Python 3.8 and add 3.13 💥
  .github/workflows/check.yaml
  Makefile
  README.md
  combadge/_helpers/pydantic.py
  combadge/core/backend.py
  combadge/core/binder.py
  combadge/core/errors.py
  combadge/core/markers/base.py
  combadge/core/markers/response.py
  combadge/core/response.py
  combadge/core/service.py
  combadge/core/signature.py
  combadge/support/http/abc/containers.py
  combadge/support/http/abc/interfaces.py
  combadge/support/http/markers/request.py
  combadge/support/http/markers/response.py
  combadge/support/httpx/backends/async_.py
  combadge/support/httpx/backends/sync.py
  combadge/support/zeep/backends/base.py
  combadge/support/zeep/backends/sync.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/core/markers/test_parameter.py
  tests/core/test_binder.py
  tests/integration/test_country_info_service.py
  tests/integration/test_docs.py
  tests/integration/test_httpbin.py
  tests/integration/test_number_conversion.py
  tests/integration/test_weather.py
  tests/support/http/test_markers.py
Labels: breaking-change

#136 NEW: `QueryArrayParam` marker for HTTP GET parameters ✨
  combadge/support/http/markers/request.py
  tests/integration/test_httpbin.py
Labels: enhancement
